apiVersion: v1
kind: Secret
metadata:
  name: {{ template "smtp.fullname" . }}
  labels:
    app: "{{ template "smtp.name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  smtp_password: "{{ default "123456" .Values.SMTP_PASSWORD | b64enc }}"
