dependencies:
- name: mariadb
  version: 5.5.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mariadb.enabled
  tags:
    - wordpress-database
- name: memcached
  version: 2.5.0
  condition: memcached.enabled
- name: rrdcached 
  version: 1.0.0
  condition: rrdcached.enabled
- name: smtp 
  version: 1.0.0
  condition: smtp.enabled
